version: '3.8'
services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  tests:
    build: .
    container_name: warehouse-tests
    command: [ "pytest", "--disable-warnings", "-v" ]
    environment:
      - DATABASE_URL="sqlite:///:memory:"
    volumes:
      - .:/app
#    depends_on:
#      - db

volumes:
  postgres_data:
